name: Setup Rust and Python Environment
description: Sets up Rust and Python with Poetry dependencies

inputs:
  rust-version:
    description: "Rust version to install"
    required: false
    default: "1.89"
  workspace-path:
    description: "The directory path to store test results"
    required: false
    default: "workflow"
  python-version:
    description: "Python version to use"
    required: false
    default: "3.12"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Display Version Info
      shell: bash
      run: |
        if [ "$(which rustc)" != "" ]; then rustc --version; fi
        if [ "$(which python)" != "" ]; then python --version; fi
        uname -a
        cat /etc/os-release

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ inputs.rust-version }}
        components: rustfmt, clippy

    - name: Install cargo-audit
      shell: bash
      run: cargo install --locked cargo-audit

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install Poetry with uv
      shell: bash
      run: uv pip install poetry

    - name: Create workspace directory
      shell: bash
      run: mkdir -p ${{ inputs. workspace-path }}

    - name: Install Python dependencies with Poetry
      shell: bash
      run: |
        poetry install --with tokenserver-unit-tests,dev --no-interaction --no-ansi
