version: '3'
services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - "3306"
        environment:
            #MYSQL_RANDOM_ROOT_PASSWORD: yes
            MYSQL_ROOT_PASSWORD: random
            MYSQL_DATABASE: syncstorage
            MYSQL_USER: test
            MYSQL_PASSWORD: test

    syncstorage-rs:
        image: ${SYNCSTORAGE_RS_IMAGE:-syncstorage-rs:latest}
        restart: always
        ports:
          - "8000:8000"
        depends_on:
          - db
        environment:
          SYNC_HOST: 0.0.0.0
          SYNC_MASTER_SECRET: secret0
          SYNC_DATABASE_URL: mysql://test:test@db:3306/syncstorage

volumes:
    db_data:

# Application runs off of port 8000.
# you can test if it's available with
# curl "http://localhost:8000/__heartbeat__"
