[package]
name = "syncstorage-settings"
version.workspace=true
license.workspace=true
authors.workspace=true
edition.workspace=true

[dependencies]
rand.workspace=true
serde.workspace=true

syncserver-common = { path = "../syncserver-common" }
time = "^0.3"
