-- user_collections table
CREATE TABLE user_collections (
    user_id BIGINT NOT NULL,
    collection_id INTEGER NOT NULL,
    modified TIMESTAMPTZ NOT NULL,
    count BIGINT,
    total_bytes BIGINT,
    PRIMARY KEY (user_id, collection_id)
);

-- bsos table
CREATE TABLE bsos (
    user_id BIGINT NOT NULL,
    collection_id INTEGER NOT NULL,
    bso_id TEXT NOT NULL,
    sortindex INTEGER,
    payload TEXT NOT NULL,
    modified TIMESTAMPTZ NOT NULL,
    expiry TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (
        user_id,
        collection_id,
        bso_id
    ),
    FOREIGN KEY (user_id, collection_id) REFERENCES user_collections (user_id, collection_id) ON DELETE CASCADE
);

CREATE INDEX bsos_modified_idx ON bsos (
    user_id,
    collection_id,
    modified DESC
);

CREATE INDEX bsos_expiry_idx ON bsos (
    user_id,
    collection_id,
    expiry
);

-- collections table
CREATE TABLE collections (
    collection_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL UNIQUE
);

-- Insert Standard Collections.
-- These are the 13 standard collections that are expected to exist by clients.
-- The IDs are fixed.
-- Reserved spaces for additions to the standard collections begin after 100.
INSERT INTO collections (collection_id, name) VALUES
    ( 1, 'clients'),
    ( 2, 'crypto'),
    ( 3, 'forms'),
    ( 4, 'history'),
    ( 5, 'keys'),
    ( 6, 'meta'),
    ( 7, 'bookmarks'),
    ( 8, 'prefs'),
    ( 9, 'tabs'),
    (10, 'passwords'),
    (11, 'addons'),
    (12, 'addresses'),
    (13, 'creditcards');

-- Set subsequent values to insert after 100.
ALTER TABLE collections 
ALTER COLUMN collection_id RESTART WITH 101;

-- batches table
CREATE TABLE batches (
    user_id BIGINT NOT NULL,
    collection_id INTEGER NOT NULL,
    batch_id UUID NOT NULL,
    expiry TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (
        user_id,
        collection_id,
        batch_id
    ),
    FOREIGN KEY (user_id, collection_id) REFERENCES user_collections (user_id, collection_id) ON DELETE CASCADE
);

CREATE INDEX batch_expiry_idx ON batches (
    user_id,
    collection_id,
    expiry
);

-- batch_bsos table
CREATE TABLE batch_bsos (
    user_id BIGINT NOT NULL,
    collection_id INTEGER NOT NULL,
    batch_id UUID NOT NULL,
    batch_bso_id TEXT NOT NULL,
    sortindex INTEGER,
    payload TEXT,
    ttl BIGINT,
    PRIMARY KEY (
        user_id,
        collection_id,
        batch_id,
        batch_bso_id
    ),
    FOREIGN KEY (
        user_id,
        collection_id,
        batch_id
    ) REFERENCES batches (
        user_id,
        collection_id,
        batch_id
    ) ON DELETE CASCADE
);

