INSERT IGNORE INTO collections (name, collectionid) VALUES
        ("clients", 1),
        ("crypto", 2),
        ("forms", 3),
        ("history", 4),
        ("keys", 5),
        ("meta", 6),
        ("bookmarks", 7),
        ("prefs", 8),
        ("tabs", 9),
        ("passwords", 10),
        ("addons", 11),
        ("addresses", 12),
        ("creditcards", 13),
        ("reserved", 99);