---
name: Glean probe-scraper
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: {} # workflow-level default — deny all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  glean-probe-scraper:
    permissions:
      contents: read
      checks: write
    uses: mozilla/probe-scraper/.github/workflows/glean.yaml@a4bb2043a25548f2a9a5a0eeb3546a41c94ce78f # v1.0
